version: "3.9"

services:
  ml:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emg-ml
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - emg-net

networks:
  emg-net:
    external: true
